root: /blog/
permalink: /:month-:day-:year/:title.html

# Theme settings
theme:

  # Site name
  site_name: Stanley Tan

  # Google analytics UID
  google_analytics_uid: 

  # Disqus shortname, for comments
  disqus_shortname: 

  # Number of featured posts on homepage
  homepage_featured: 1

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 2

  # Number of words to display in post summaries
  featured_wordcount: 20